[build]
  publish = "."
  command = ""

[context.production.environment]
  # Example env var placeholders
  # OMDB_API_KEY = "${OMDB_API_KEY}"

[[[plugins]]]
package = "@netlify/plugin-functions-core"

[dev]
  command = ""
  port = 8888

[headers]
  # caching hints for static assets
  [[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

  [[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
